var annotated_dup =
[
    [ "AnimationManagement", "class_animation_management.html", "class_animation_management" ],
    [ "ASNode", "class_a_s_node.html", "class_a_s_node" ],
    [ "AStarSearch", "class_a_star_search.html", "class_a_star_search" ],
    [ "BodyComponent", "struct_body_component.html", "struct_body_component" ],
    [ "BTAction", "class_b_t_action.html", "class_b_t_action" ],
    [ "BTNode", "class_b_t_node.html", "class_b_t_node" ],
    [ "BTSequence", "class_b_t_sequence.html", "class_b_t_sequence" ],
    [ "CameraControl", "class_camera_control.html", "class_camera_control" ],
    [ "CareProperty", "class_care_property.html", "class_care_property" ],
    [ "Controller", "class_controller.html", "class_controller" ],
    [ "DataDisplay", "class_data_display.html", "class_data_display" ],
    [ "Dog", "class_dog.html", "class_dog" ],
    [ "DogGeneration", "class_dog_generation.html", "class_dog_generation" ],
    [ "FiniteStateMachine", "class_finite_state_machine.html", "class_finite_state_machine" ],
    [ "GameTime", "class_game_time.html", "class_game_time" ],
    [ "GetUIComponent", "class_get_u_i_component.html", "class_get_u_i_component" ],
    [ "Heap", "class_heap.html", "class_heap" ],
    [ "Hungry", "class_hungry.html", "class_hungry" ],
    [ "Idle", "class_idle.html", "class_idle" ],
    [ "IHeapElement", "interface_i_heap_element.html", "interface_i_heap_element" ],
    [ "Item", "class_item.html", "class_item" ],
    [ "ItemInstance", "class_item_instance.html", "class_item_instance" ],
    [ "ItemSlot", "class_item_slot.html", "class_item_slot" ],
    [ "ModelOrientation", "struct_model_orientation.html", null ],
    [ "Pathfinding", "class_pathfinding.html", "class_pathfinding" ],
    [ "Pause", "class_pause.html", "class_pause" ],
    [ "PersonalityProperty", "class_personality_property.html", "class_personality_property" ],
    [ "Playful", "class_playful.html", "class_playful" ],
    [ "Rule", "class_rule.html", "class_rule" ],
    [ "State", "class_state.html", "class_state" ],
    [ "StoreController", "class_store_controller.html", "class_store_controller" ],
    [ "StoreSection", "class_store_section.html", "class_store_section" ],
    [ "TipPopUp", "class_tip_pop_up.html", "class_tip_pop_up" ],
    [ "Tired", "class_tired.html", "class_tired" ]
];